//Import from react
import { FC, useState } from 'react';

//Import from chakra 
import { Flex, Button, Box, Link } from '@chakra-ui/react';

//Import from formik
import { Formik, Form } from 'formik';

//Import from Next.js
import NextLink from 'next/link';
import router from 'next/router';

//import other components
import InputField from '../components/InputField';
import Wrapper from '../components/Wrapper';

//Import utils
import { toErrorMap } from '../utils/toErrorMap';

//Import urql stuff
import { withUrqlClient } from 'next-urql';
import createUrqlClient from '../utils/createUrqlClient';

//Import autogenerated stuff
import { useForgotPasswordMutation } from '../generated/graphql';

const ForgotPassword: FC<{}> = ({ }) => {

    const [isComplete, setIsComplete] = useState(false);
    const [, forgotPassword] = useForgotPasswordMutation()

    return (
        <Wrapper>
            <Formik 
                initialValues={{email: ''}}
                onSubmit={async (values, { setErrors }) => {
                    const response = await forgotPassword({ email: values.email });
                    if(response.data?.forgotPassword.error) {
                        setErrors({
                            email: response.data?.forgotPassword.error.message
                        })
                        return;
                    } 
                    
                    setIsComplete(true);
                }}    
            >
                {({values, handleChange, isSubmitting}) =>
                    isComplete ? 
                    <Box>
                        Please, check your e-mail inbox
                    </Box>
                :
                (
                    <Form>
                        <InputField
                            name='email'
                            placeholder='Please, type in your email'
                            label='E-mail'
                        />
                        <Button 
                            mt={10} 
                            mx={'auto'} 
                            backgroundColor={'turquoise'} 
                            color={'white'} 
                            type='submit'
                            isLoading={isSubmitting}
                        >
                            Send email
                        </Button>
                    </Form>
                )}
            </Formik>
        </Wrapper>
    );
}

export default withUrqlClient(createUrqlClient)(ForgotPassword);