//Import from react
import { FC, useState } from 'react';

//Import from chakra 
import { Flex, Button, Box, Text } from '@chakra-ui/react';

//Import from formik
import { Formik, Form } from 'formik';

//import other components
import InputField from '../components/InputField';
import Wrapper from '../components/Wrapper';

//Import urql stuff
import { withUrqlClient } from 'next-urql';
import createUrqlClient from '../utils/createUrqlClient';

//Import autogenerated stuff
import { useForgotPasswordMutation } from '../generated/graphql';

const ForgotPassword: FC<{}> = ({ }) => {

    const [isComplete, setIsComplete] = useState(false);
    const [, forgotPassword] = useForgotPasswordMutation()

    return (
        <Wrapper>
            <Formik 
                initialValues={{email: ''}}
                onSubmit={async (values, { setErrors }) => {
                    const response = await forgotPassword({ email: values.email });
                    if(response.data?.forgotPassword.error) {
                        setErrors({
                            email: response.data?.forgotPassword.error.message
                        })
                        return;
                    } 
                    
                    setIsComplete(true);
                }}    
            >
                {({values, isSubmitting}) =>
                    isComplete ? 
                    <Flex >
                        <Box>
                            <Text>
                                Please, check your e-mail inbox, if it is not there, check your spam folder.
                            </Text>
                            <Button
                                mt={10} 
                                mx={'auto'} 
                                backgroundColor={'turquoise'} 
                                color={'white'} 
                                onClick={() => {
                                    setIsComplete(false);
                                    values.email = '';
                                }}
                            >
                                Resend e-mail
                            </Button>
                        </Box>
                    </Flex>
                :
                (
                    <Form>
                        <InputField
                            name='email'
                            placeholder='Please, type in your email'
                            label='E-mail'
                        />
                        <Button 
                            mt={10} 
                            mx={'auto'} 
                            backgroundColor={'turquoise'} 
                            color={'white'} 
                            type='submit'
                            isLoading={isSubmitting}
                        >
                            Send email
                        </Button>
                    </Form>
                )}
            </Formik>
        </Wrapper>
    );
}

export default withUrqlClient(createUrqlClient)(ForgotPassword);